#config_version=6

show_player:
  mode_attract_started:
    attract_display_loop:
      speed: 1
    #attract_light_show:
    #  speed: 4

sound_player:
  mode_attract_started:
    hail_purdue:
      action: play
      loops: -1