#config_version=6

mode:
  start_events: ball_started
  priority: 100

slide_player:
  mode_base_started:
    widgets:
      - type: text
        text: (score)
        number_grouping: true
        min_digits: 2
        font_size: 100
      - type: text
        text: PLAYER (number)
        y: 10
        x: 10
        font_size: 50
        anchor_x: left
        anchor_y: bottom
      - type: text
        text: BALL (ball)
        y: 10
        x: right-10
        anchor_x: right
        anchor_y: bottom
        font_size: 50

variable_player:
  s_left_spinner_active:
    score: 200
  s_right_spinner_active:
    score: 100
  s_bottom_standup_active:
    score: 500
  s_middle_standup_active:
    score: 500
  s_top_standup_active:
    score: 500
  s_right_upperlane_active:
    score: 100
  s_middle_upperlane_active:
    score: 100
  s_left_upperlane_active:
    score: 100
  s_train_drop_active:
    score: 1000
  s_train_rollover_active:
    score: 1000
  s_left_outerlane_active:
    score: 100
  s_left_innerlane_active:
    score: 100
  s_right_outerlane_active:
    score: 100
  s_right_innerlane_active:
    score: 100
  s_top_bumper_active:
    score: 200
  s_middle_bumper_active:
    score: 200
  s_bottom_bumper_active:
    score: 200
  s_left_top_slingshot_active:
    score: 100
  s_left_bottom_slingshot_active:
    score: 100
  s_right_top_slingshot_active:
    score: 100
  s_right_bottom_slingshot_active:
    score: 100

shot_groups:
  rollover_lanes:
    shots: left_lane, middle_lane, right_lane
    rotate_left_events: s_left_flipper
    rotate_right_events: s_right_flipper
  standups:
    shots: standup_1, standup_2, standup_3

shots:
  left_lane:
    switch: s_left_upperlane
    #show_tokens:
    #  light: l_left_rollover
  middle_lane:
    switch: s_middle_upperlane
    #show_tokens:
    #  light: l_middle_rollover
  right_lane:
    switch: s_right_upperlane
    #show_tokens:
    #  light: l_right_rollover
  standup_1:
    switch: s_top_standup
    #show_tokens:
    #  light: l_standup_1
  standup_2:
    switch: s_middle_standup
    #show_tokens:
    #  light: l_standup_2
  standup_3:
    switch: s_bottom_standup
    #show_tokens:
    #  light: l_standup_3
  center_ramp:
    switch: s_left_spinner