#config_version=6

hardware:
   platform: opp
   driverboards: gen2

opp:
   ports: /dev/ttyACM0, /dev/ttyACM1

psus:
  default:
    release_wait_ms: 50

game:
  balls_per_game: 3
  max_players: 1

switches:
  s_left_flipper:
    number: 0-0-1 # number is from switch input
    tags: left_flipper
  s_right_flipper:
    number: 0-0-3
    tags: right_flipper
  s_right_flipper_EOS:
    number: 0-0-8
    tags: right_EOS
  s_left_flipper_EOS:
    number: 0-0-9
    tags: left_EOS
  s_start:
    number: 0-0-2
    tags: start
  s_trough1:
    number: 0-0-10
    tags: trough_ball1
  s_trough2:
    number: 0-0-11
    tags: trough_ball2
  s_left_spinner:
    number: 0-0-24
    tags: left_spinner
    type: NC
  s_right_spinner:
    number: 1-0-9
    tags: right_spinner
    type: NC
  s_bottom_standup:
    number: 0-0-27
    tags: bottom_standup
    type: NC
  s_middle_standup:
    number: 0-0-25
    tags: middle_standup
    type: NC
  s_top_standup:
    number: 0-0-26
    tags: ptop_standup
    type: NC
  s_right_upperlane:
    number: 1-0-18
    tags: playfield_active
    type: NC
  s_middle_upperlane:
    number: 1-0-17
    tags: playfield_active
    type: NC
  s_left_upperlane:
    number: 1-0-16
    tags: playfield_active
    type: NC
  s_train_rollover:
    number: 1-0-19
    tags: train_rollover
    type: NC
  s_train_drop:
    number: 1-0-20
    tags: train_drop
  s_left_outerlane:
    number: 1-0-1
    tags: outerlane
    type: NC
  s_left_innerlane:
    number: 1-0-2
    tags: innerlane
    type: NC
  s_right_outerlane:
    number: 1-0-3
    tags: outerlane
    type: NC
  s_right_innerlane:
    number: 1-0-8
    tags: innerlane
    type: NC
  s_top_bumper:
    number: 1-0-21
    tags: top_bumper
  s_middle_bumper:
    number: 1-0-22
    tags: middle_bumper
  s_bottom_bumper:
    number: 1-0-23
    tags: bottom_bumper
  s_left_top_slingshot:
    number: 0-0-19
    tags:
  s_left_bottom_slingshot:
    number: 0-0-18
    tags:
    type: NC
  s_right_top_slingshot:
    number: 0-0-17
    tags:
    type: NC
  s_right_bottom_slingshot:
    number: 0-0-16
    tags:
    type: NC

coils:
  c_flipper_left_main:
    number: 0-0-3 # number from switch input
    allow_enable: true
    default_hold_power: 0.5
    default_pulse_ms: 200
  c_flipper_right_main:
    number: 0-0-4
    allow_enable: true
    default_hold_power: 0.5
    default_pulse_ms: 200
  c_trough_eject:
    number: 0-0-2
    default_pulse_ms: 70
  c_bumper_top:
    number: 1-0-0
    default_pulse_ms: 50
  c_bumper_middle:
    number: 1-0-7
    default_pulse_ms: 50
  c_bumper_bottom:
    number: 1-0-6
    default_pulse_ms: 50
  c_scoop_eject:
    number: 1-0-5
  c_left_slingshot:
    number: 0-0-5
  c_right_slingshot:
    number: 0-0-6

#servos:
#  servo1:
#    servo_min: 0.1
#    servo_max: 0.9
#    positions:
#      0.0: servo1_down
#      0.8: servo1_up
#    reset_position: 0.8
#    reset_events: reset_servo1
#    number: 1-0-10

#shows:
#  train_hit:
#    - duration: 2s
#      events: reset_servo1
#show_player:
#  ball_ended:
#    train_hit:
#      loops: 1

spinners:
  ramp_spinner:
    switch: s_left_spinner
    active_ms: 500
  return_spinner:
    switch: s_right_spinner
    active_ms: 500

flippers:
  left_flipper:
    main_coil: c_flipper_left_main
    activation_switch: s_left_flipper
    #eos_switch: s_left_flipper_EOS
    #use_eos: true
    #repulse_on_eos_open: true
    #eos_active_ms_before_repulse: 500
  right_flipper:
    main_coil: c_flipper_right_main
    activation_switch: s_right_flipper
    #eos_switch: s_right_flipper_EOS
    #use_eos: true
    #repulse_on_eos_open: true
    #eos_active_ms_before_repulse: 500

ball_devices:
  bd_trough:
    ball_switches: s_trough1 #, s_trough2
    mechanical_eject: true #eject_coil: c_trough_eject
    tags: trough, home, drain
    debug: true

autofire_coils:
  #left_slingshot_top:
  #  coil: c_left_slingshot
  #  switch: s_left_top_slingshot
  #left_slingshot_bottom:
  #  coil: c_left_slingshot
  #  switch: s_left_bottom_slingshot
  #right_slingshot_top:
  #  coil: c_right_slingshot
  #  switch: s_right_top_slingshot
  #right_slingshot_bottom:
  #  coil: c_right_slingshot
  #  switch: s_right_bottom_slingshot
  top_bumper:
    coil: c_bumper_top
    switch: s_top_bumper
  middle_bumper:
    coil: c_bumper_middle
    switch: s_middle_bumper
  bottom_bumper:
    coil: c_bumper_bottom
    switch: s_bottom_bumper
  #train_scoop:
  #  coil: c_scoop_eject
  #  switch: s_train_rollover
    #coil_pulse_delay: 300ms

playfields:
  playfield:
    tags: default
    default_source_device: bd_trough
    # ball save start event based on playfield_active

displays:
  window:
    width: 800
    height: 600

slides:
  welcome_slide:
    widgets:
      - type: image
        image: welcome_intro
        scale: 1

slide_player:
  init_done: welcome_slide

light_stripes:
  led_strip_0:
    number_start: 0
    count: 50
    number_template: 0-0-{}
    light_template:
      type: rgb
      tags: strip0

light_player:
  full_strip_on:
    strip0: DFFF00

sound_player:
  init_done:
    train_whistle:
      action: play
  mode_attract_started:
    hail_purdue:
      action: play
      loops: -1
  mode_attract_stopped:
    hail_purdue:
      action: stop
  mode_train_drop_started:
    train_whistle:
      action: play

machine_vars:
  master_volume:
    initial_value: 0.5   # Set this to any value you want
    value_type: float
    persist: true

assets:
  sounds:
    default:
      load: on_demand
    music:
      track: music
    sfx:
      track: sfx
    voice:
      track: voice

sound_system:
  buffer: 1024
  channels: 1
  enabled: true
  frequency: 44100
  tracks:
    music:
      type: standard
      simultaneous_sounds: 1
      volume: 0.5
    voice:
      type: standard
      simultaneous_sounds: 1
      volume: 0.7
    sfx:
      type: standard
      simultaneous_sounds: 8
      volume: 0.7

sounds:
  train_whistle:
    file: 00 - sfx - train-whistle-306031.wav
  hail_purdue:
    file: Purdue University Hail Purdue.flac
    fade_in: 1.5s

virtual_platform_start_active_switches:
  - s_trough1
  - s_trough2

#player_vars:
#  initials:
#    value_type: str
#    initial_value: AAA

keyboard:
  1:
    switch: s_trough1
    toggle: true
  2:
    switch: s_trough2
    toggle: true
  z:
    switch: s_left_flipper
  '/':
    switch: s_right_flipper
  s:
    switch: s_start
  q:
    switch: s_right_upperlane
  t:
    switch: s_train_drop
  l:
    switch: s_right_top_slingshot

modes:
  - base
  #- high_score
  #- upperlane_combo
  #- skillshot
  #- multiball
  #- train
  #- service