#config_version=6

hardware:
   platform: opp
   driverboards: gen2

opp:
   ports: /dev/ttyACM0, /dev/ttyACM1

psus:
  default:
    release_wait_ms: 50

game:
  balls_per_game: 3
  max_players: 1

switches:
  s_left_flipper:
    number: 0-0-1 # number is from switch input
    tags: left_flipper
  s_right_flipper:
    number: 0-0-3
    tags: right_flipper
  #s_right_flipper_EOS:
  #  number: 0-0-8
  #  tags: right_EOS
  #s_left_flipper_EOS:
  #  number: 0-0-9
  #  tags: left_EOS
  s_start:
    number: 0-0-2
    tags: start
  s_trough1:
    number: 0-0-10
    tags: trough_ball1
  #s_trough2:
  #  number: 0-0-11
  #  tags: trough_ball2
  s_left_spinner:
    number: 0-0-19 #1-0-28
    tags: playfield_active, left_spinner
    type: NC
  s_right_spinner:
    number: 1-0-2
    tags: playfield_active, right_spinner
    type: NC
  s_bottom_standup:
    number: 0-0-16 #1-0-31
    tags: playfield_active, bottom_standup
    type: NC
  s_middle_standup:
    number: 0-0-17  #1-0-30
    tags: playfield_active, middle_standup
    type: NC
  s_top_standup:
    number: 0-0-18 #1-0-29
    tags: playfield_active, top_standup
    type: NC
  s_right_upperlane:
    number: 1-0-16
    tags: playfield_active
    type: NC
  s_middle_upperlane:
    number: 1-0-18
    tags: playfield_active
    type: NC
  s_left_upperlane:
    number: 1-0-17
    tags: playfield_active
    type: NC
  s_train_rollover:
    number: 1-0-19
    tags: train_rollover
    type: NC
  s_train_drop:
    number: 1-0-20
    tags: train_drop
  s_left_outerlane:
    number: 1-0-10
    tags: outerlane
  s_left_innerlane:
    number: 1-0-9
    tags: innerlane
  s_right_outerlane:
    number: 1-0-8
    tags: outerlane
    type: NC
  s_right_innerlane:
    number: 1-0-3
    tags: innerlane
    type: NC
  s_top_bumper:
    number: 1-0-21
    tags: top_bumper
  s_middle_bumper:
    number: 1-0-22
    tags: middle_bumper
  s_bottom_bumper:
    number: 1-0-23
    tags: bottom_bumper
  s_left_top_slingshot:
    number: 0-0-25 #1-0-27
    tags: left_top_slingshot
  s_left_bottom_slingshot:
    number: 0-0-24 #1-0-26
    tags: left_bottom_slingshot
  s_right_top_slingshot:
    number: 0-0-26 #1-0-25
    tags: right_top_slingshot
  s_right_bottom_slingshot:
    number: 0-0-27 #1-0-24
    tags: right_bottom_slingshot

coils:
  c_flipper_left_main:
    number: 0-0-3 # number from switch input
    allow_enable: true
    default_hold_power: 0.25 # once flipper is held
    default_pulse_ms: 175 # initial push
  c_flipper_right_main:
    number: 0-0-4
    allow_enable: true
    default_hold_power: 0.25
    default_pulse_ms: 175
  c_trough_eject:
    number: 0-0-2
    default_pulse_ms: 70
  c_bumper_top:
    number: 1-0-0
    default_pulse_ms: 150
  c_bumper_middle:
    number: 1-0-6
    default_pulse_ms: 150
  c_bumper_bottom:
    number: 1-0-7
    default_pulse_ms: 150
  c_scoop_eject:
    number: 1-0-5
  c_left_slingshot:
    number: 0-0-5 #1-0-2
    default_pulse_ms: 150
  c_right_slingshot:
    number: 0-0-6 #1-0-3
    default_pulse_ms: 150
  c_turntable_right:
    number: 0-0-8
    default_pulse_power: 0.25
    default_hold_power: 0.125

coil_player:
  ball_started:
    c_turntable_right:
      action: enable
  ball_ended:
    c_turntable_right:
      action: disable
  game_ended:
    c_turntable_right:
      action: disable

timed_switches:
  game_cancel:
    switch_tags: start
    time: 3s
    events_when_active: end_game

#servos:
#  servo1:
#    servo_min: 0.1
#    servo_max: 0.9
#    positions:
#      0.0: servo1_down
#      0.8: servo1_up
#    reset_position: 0.8
#    reset_events: reset_servo1
#    number: 1-0-10

#diverters:
#  d_diverter:
#    debug: true
#    feeder_devices: bd_trough
#    targets_when_active: playfield
#    targets_when_inactive: bd_scoop

#motors:
#  m_diverter:
#    motor_left_output: c_turntable_left
#    motor_right_output: c_turntable_right
#    position_switches:  !!omap
#    - pos2: s_turntable_start
 #   - home: s_turntable_home
 #   - pos1: s_turntable_end
 #   reset_position: home
 #   go_to_position:
#      stop_turntable: ball_ended
  #    go_pos1: pos1
  #    go_pos2: pos2
  #  debug: true

#shows:
#  train_hit:
#    - duration: 2s
#      events: reset_servo1
#show_player:
#  ball_ended:
#    train_hit:
#      loops: 1

spinners:
  ramp_spinner:
    switch: s_left_spinner
    active_ms: 500
  return_spinner:
    switch: s_right_spinner
    active_ms: 500

flippers:
  left_flipper:
    main_coil: c_flipper_left_main
    activation_switch: s_left_flipper
    #eos_switch: s_left_flipper_EOS
    #use_eos: true
    #repulse_on_eos_open: true
    #eos_active_ms_before_repulse: 500
  right_flipper:
    main_coil: c_flipper_right_main
    activation_switch: s_right_flipper
    #eos_switch: s_right_flipper_EOS
    #use_eos: true
    #repulse_on_eos_open: true
    #eos_active_ms_before_repulse: 500

ball_devices:
  bd_trough:
    ball_switches: s_trough1 #, s_trough2
    eject_coil: c_trough_eject #mechanical_eject: true #eject_coil: c_trough_eject
    tags: trough, home, drain
    eject_targets: playfield
    eject_timeouts: 5s
    debug: true
  bd_scoop:
    eject_coil: c_scoop_eject
    ball_switches: s_train_rollover
    eject_timeouts: 2s


autofire_coils:
  left_slingshot_top:
    coil: c_left_slingshot
    switch: s_left_top_slingshot
  left_slingshot_bottom:
    coil: c_left_slingshot
    switch: s_left_bottom_slingshot
  right_slingshot_top:
    coil: c_right_slingshot
    switch: s_right_top_slingshot
  right_slingshot_bottom:
    coil: c_right_slingshot
    switch: s_right_bottom_slingshot
  top_bumper:
    coil: c_bumper_top
    switch: s_top_bumper
  middle_bumper:
    coil: c_bumper_middle
    switch: s_middle_bumper
  bottom_bumper:
    coil: c_bumper_bottom
    switch: s_bottom_bumper

playfields:
  playfield:
    tags: default
    default_source_device: bd_trough
    # ball save start event based on playfield_active

displays:
  window:
    width: 800
    height: 480

slides:
  welcome_slide:
    widgets:
      - type: image
        image: welcome_intro
        scale: 1

slide_player:
  init_done: welcome_slide

light_stripes:
  led_strip_0:
    number_start: 0
    count: 50
    number_template: 0-0-{}
    light_template:
      type: rgb
      tags: strip0

light_player:
  full_strip_on:
    strip0: DFFF00

sound_player:
  init_done:
    train_whistle:
      action: play
  mode_attract_started:
    hail_purdue:
      action: play
      loops: -1
  mode_attract_stopped:
    hail_purdue:
      action: stop
  mode_train_drop_started:
    train_whistle:
      action: play

machine_vars:
  master_volume:
    initial_value: 0.5   # Set this to any value you want
    value_type: float
    persist: true

assets:
  sounds:
    default:
      load: on_demand
    music:
      track: music
    sfx:
      track: sfx
    voice:
      track: voice

sound_system:
  buffer: 1024
  channels: 1
  enabled: true
  frequency: 44100
  tracks:
    music:
      type: standard
      simultaneous_sounds: 1
      volume: 0.5
    voice:
      type: standard
      simultaneous_sounds: 1
      volume: 0.7
    sfx:
      type: standard
      simultaneous_sounds: 8
      volume: 0.7

sounds:
  train_whistle:
    file: 00 - sfx - train-whistle-306031.wav
  hail_purdue:
    file: Purdue University Hail Purdue.flac
    fade_in: 1.5s

virtual_platform_start_active_switches:
  - s_trough1

player_vars:
  initials:
    value_type: str
    initial_value: AAA

keyboard:
  1:
    switch: s_trough1
    toggle: true
  z:
    switch: s_left_flipper
  '/':
    switch: s_right_flipper
  s:
    switch: s_start
  q:
    switch: s_right_upperlane
  t:
    switch: s_train_drop
  y:
    switch: s_train_rollover
  l:
    switch: s_right_top_slingshot

modes:
  - base
  - hold1
  #- high_score
  #- upperlane_combo
  #- skillshot
  #- multiball
  #- train
  #- service