#config_version=6

game:
  balls_per_game: 3
  max_players: 1

switches:
  s_left_flipper:
    number: # number is from switch input
    tags: left_flipper
  s_right_flipper:
    number:
    tags: right_flipper
  s_right_flipper_EOS:
    number:
    tags: right_EOS
  s_left_flipper_EOS:
    number:
    tags: left_EOS
  s_trough1:
    number:
  s_start:
    number:
    tags: start
  s_right_upperlane:
    number:
    tags: playfield_active
  s_middle_upperlane:
    number:
    tags: playfield_active
  s_left_upperlane:
    number:
    tags: playfield_active

coils:
  c_flipper_left_main:
    number: # number from switch input
    default_pulse_ms: 10
  c_flipper_left_hold:
    number:
    allow_enable: true
    default_hold_power: 0.125
  c_flipper_right_main:
    number:
    default_pulse_ms: 10
  c_flipper_right_hold:
    number:
    allow_enable: true
    default_hold_power: 0.125
  c_trough_eject:
    number:

playfields:
  playfield:
    tags: default
    default_source_device: bd_trough
    # ball save start event based on playfield_active

displays:
  window:
    width: 800
    height: 600

slides:
  welcome_slide:
    widgets:
      - type: text
        text: PINBALL!
        font_size: 50
        color: red
      - type: rectangle
        width: 240
        height: 60

slide_player:
  init_done: welcome_slide

flippers:
  left_flipper:
    main_coil: c_flipper_left_main
    hold_coil: c_flipper_left_hold
    activation_switch: s_left_flipper
    eos_switch: s_left_flipper_EOS
  right_flipper:
    main_coil: c_flipper_right_main
    hold_coil: c_flipper_right_hold
    activation_switch: s_right_flipper
    eos_switch: s_right_flipper_EOS

ball_devices:
  bd_trough:
    ball_switches: s_trough1
    eject_coil: c_trough_eject
    tags: trough, home, drain
    debug: true

virtual_platform_start_active_switches:
  - s_trough1


keyboard:
  1:
    switch: s_trough1
    toggle: true
  z:
    switch: s_left_flipper
  '/':
    switch: s_right_flipper
  s:
    switch: s_start
  q:
    switch: s_right_upperlane

modes:
  - base
  #- skillshot
  #- multiball
  #- train