#config_version=6
##! mode: hold1
mode:
  restart_on_next_ball: true
  start_events: ball_started
ball_holds:
  hold1:
    hold_devices: bd_scoop
    balls_to_hold: 1
    enable_events: s_train_drop_active
    disable_events: end_hold
    release_one_events: end_hold